# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include:
      - main

variables:
  # Azure Resource Manager connection created during pipeline creation
  pythonVersion: '3.7'
  azureServiceConnectionId: '3b7ef9f3-48fc-4d29-a9f8-3de02b79dac0'
  projectRoot: $(System.DefaultWorkingDirectory)
  webAppName: 'sy-test-app'
  environmentName: 'sy-test-app'

pool: ubuntu-local

jobs:
- job: BuildJob
  displayName: 'Build'
  pool: ubuntu-local

  steps:
  - script: |
      python -m venv antenv
      source antenv/bin/activate
      python -m pip install --upgrade pip
      pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
    workingDirectory: $(projectRoot)
    displayName: "Install requirements"

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(projectRoot)'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: 'Upload package'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      ArtifactName: 'drop'

  - task: AzureWebApp@1
    displayName: 'Azure Web App Deploy: python-sample-vscode-flask-tutorial'
    inputs:
      azureSubscription: $(azureServiceConnectionId)
      appName: $(webAppName)
      package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip

